# Generated by Django 5.0.6 on 2024-08-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='coursel/images')),
                ('title', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=70)),
            ],
        ),
    ]
